use master

CREATE DATABASE CursBD ON PRIMARY
(NAME = N'CursBD',
FILENAME = N'C:\bd\CursBD.mdf' ,
SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
LOG ON
( NAME = N'CursBD_log',
FILENAME = N'C:\bd\CursBD.ldf' ,
SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)

